Homework 1
xznex/2022-2-VK-EDU-FS-Frontend-E-Zernin pull request #1
Opened 2022-10-05 21:31 UTC by xznex

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
* код к convertBytesToHuman.js, correctSentence.js, nonUniquieElements.js
* тест для convertBytesToHuman.js

С уважением, Dbaldnc (tg) :)

2022-10-10 19:42 UTC, martinkomitsky commented on pull_request_template.md
> +# Домашнее задание №1
У тебя произошел конфликт в гите, который надо разрезолвить.
Более того, шаблон PR на то и шаблон, что остается неизменным. Оставь его в таком формате, в каком он давался в инструкции, а меняй содержимое уже напрямую при создании реквеста

2022-10-10 19:42 UTC, martinkomitsky requested changes
См. коммент

2022-10-10 19:43 UTC, martinkomitsky commented on pull_request_template.md
> +# Домашнее задание №1
<img width="979" alt="image" src="https://user-images.githubusercontent.com/14847018/194941063-185fd80c-df05-4d9a-a7c7-322086a21ae3.png">

2022-10-12 23:43 UTC, HaseProgram approved these changes
Поправлено, по остальному замечаний нет, 12

2022-10-13 11:59 UTC, martinkomitsky approved these changes

2022-10-13 11:59 UTC, merged